### ISSUE TITLE
보안관련 이슈

### ISSUE THREAD

**Issue by okinawaa** [ssi02014/chat-app#1]
안녕하세요 레포지토리 잘 보고있습니다.

.env 파일이 해당 레포지토리에 업로드되었는데
gitignore에서 관리하시는건 어떠신가요?!

**Comment by ssi02014** [comment]
헉스 !! 단순 공부 레포도 봐주시는군요 너무나 감사드립니다 🙇‍♂️ 현재 env파일은 의도적으로 올려놓은 것이라 추후에 조치 할 예정입니다!!

**Comment by okinawaa** [comment]
오! 답변감사합니다~!~! 
저도 아직 많이 공부하는 입장이라 항상레포 참고하고있습니다!
감사합니다!
